---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on RedHat nodes
    dnf:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"