---
- hosts: all
  tasks:
  - name: i want to install webserver on unbuntu
    apt:
      name: apache2
      state: present

  - name: i want to start webserver on unbuntu
    service:
      name: apache2
      state: started